# Generated by Django 2.2 on 2019-04-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='类目名')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '类目',
                'verbose_name_plural': '类目',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='型号')),
                ('oe', models.TextField(default='', verbose_name='OE号')),
                ('keywords', models.CharField(max_length=200, verbose_name='关键词')),
                ('intro', models.CharField(max_length=200, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='价格')),
                ('image', models.ImageField(blank=True, upload_to='product/', verbose_name='产品图片')),
                ('car', models.CharField(max_length=200, verbose_name='适用车辆')),
                ('net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='净重')),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='毛重')),
                ('pcs_carton', models.IntegerField(blank=True, null=True, verbose_name='每箱数量')),
                ('means', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='长*宽*高')),
                ('active', models.BooleanField(default=True, verbose_name='是否在售')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详细说明')),
                ('amazon', models.URLField(blank=True, null=True, verbose_name='亚马逊链接')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Category', verbose_name='类目')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ('-created',),
            },
        ),
    ]
